services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    volumes:
      - ./config:/config:ro
      - /etc/localtime:/etc/localtime:ro
      - ${SECRETS_DIR}/cloudflared:/etc/cloudflared:ro
    environment:
      - TZ=Asia/Kolkata
      - LOG_LEVEL=info
    command: tunnel --config /config/config.yml run