services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    volumes:
      - ./config:/config:ro
      - /etc/localtime:/etc/localtime:ro
      - ${SECRETS_DIR}/cloudflared/${CLOUDFLARE_TUNNEL_ID}.json:/etc/cloudflared/credentials.json:ro
    environment:
      - TZ=Asia/Kolkata
      - LOG_LEVEL=info
      - CLOUDFLARE_TUNNEL_ID=${CLOUDFLARE_TUNNEL_ID}
    command: tunnel --config /config/config.yml run