services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    volumes:
      - ./config.yaml:/home/nonroot/.cloudflare/config.yaml:ro
      - ${SECRETS_DIR}/cloudflared:/home/nonroot/secrets:ro
    environment:
      - TZ=Asia/Kolkata
      - LOG_LEVEL=info
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    command: tunnel --config /home/nonroot/.cloudflare/config.yaml run